name: Build

on: [push]

jobs:
  build-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # - run: nix-shell
      - run: yarn install
      - run: yarn prettier:check
      - run: yarn build
