name: Build

on: [push]

jobs:
  build-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix-shell
      - run: yarn install
      - run: yarn prettier:check
      - run: yarn build

  check-terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix-shell
      - run: cd deployment
      - run: tflint
      - run: tofu fmt -check *.tf
