name: Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch: {}

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: ${{ secrets.AWS_SESSION_NAME }}
          aws-region: ${{ secrets.WEBSITE_BUCKET_REGION }}
      - run: nix-shell --run "yarn install"
      - run: nix-shell --run "yarn build"
      - run:
          nix-shell --run "aws --region ${{ secrets.WEBSITE_BUCKET_REGION }} s3
          sync ./dist \"s3://${{ secrets.WEBSITE_BUCKET_NAME }}\" --delete
          --exclude \"images\""
